feat: new smart contracts abi
deepsquare-io/deepsquare-client pull request #17
Opened 2023-06-06 10:00 UTC by efelem

In the file src/graphql/client/generated/graphql.ts:

- A new type Bore is added, representing a proxy for exposing TCP sockets.
- The HttpData type is renamed to HTTPData.
- The Step type is modified to include new properties such as dependsOn, launch, and name.

In the file src/grpc/client.ts:

- The createLoggerClient function now accepts a loggerEndpoint parameter.
-The host property in the GrpcTransport configuration is updated to use the loggerEndpoint parameter. In the file src/index.ts:

- The jobDurationInMinutes function is added to calculate the duration of a job.
-  The computeCost function now returns a number instead of a bigint.
- The bigIntToNumber function is added to convert a bigint to a number.
- The computeCostPerMin function now returns a number instead of a bigint.
- The DeepSquareClient class has several changes:
 - The loggerClientFactory parameter in the constructor now accepts a loggerEndpoint parameter.
 - The jobDurationInMinutes function is used to calculate the duration of a job.
 - The computeCost and computeCostPerMin functions return numbers instead of bigint.
 - The getJob method includes additional properties: actualCost, costPerMin, timeLeft, and duration.
 - The getLogsMethods method now accepts a loggerEndpoint parameter.

2023-06-08 15:01 UTC, Darkness4 requested changes

2023-06-08 15:01 UTC, Darkness4 commented on src/index.ts
> +    ? Number(job.cost.finalCost.toBigInt() / (1000000000000000000n * 1000n)) /
Please justify this magic number.

2023-06-08 15:08 UTC, Darkness4 requested changes

2023-06-08 15:08 UTC, Darkness4 commented on src/index.ts
> +    uses = []
Incorrect typing. Please put the corret type corresponding to the ABI.

2023-06-09 08:47 UTC, efelem commented on src/index.ts
> +    Number(bint / (1000000000000000000n / BigInt(Math.pow(10, decimals)))) /
Why using bigint for things that are always small and where we don't need 18 decimals. Smart contract team decided to put everything in bigint. But to use the sdk getting big int is painfull (cannot serialize in json). Why forcing bigint if we know we don't need that level of precision ? Here we divide by 18 decimals to go from bigint to int but we use the formula to get decimal numbers with a certain precision. So that you can get a cost of 0.001 credits which should be enough. Any thoughts @Darkness4 ?

2023-06-09 08:50 UTC, efelem commented on src/index.ts
> +    loggerEndpoint = "grid-logger.deepsquare.run:443"
does this mean that somebody using the sdk on the beta environment will have to have extra code elsewhere ? 
e.g. write 

```
export function createDevLoggerClient(): LoggerAPIClient {
  const transport = new GrpcTransport({
    host: "dev_logger_url",
    channelCredentials: ChannelCredentials.createSsl(),
  });
  return new LoggerAPIClient(transport);
}
```

2023-06-09 08:50 UTC, efelem commented on src/index.ts
> -): bigint {
see comment below

2023-06-09 08:52 UTC, efelem commented on src/index.ts
> +): number {
Here we divide by 10e18. I think we loose precision but how could we overflow ?

2023-06-09 08:58 UTC, Darkness4 commented on src/index.ts
> +    Number(bint / (1000000000000000000n / BigInt(Math.pow(10, decimals)))) /
Because of ieee754, any floating has the capablity to loose information. Also, it isn't the responsibility of the SDK to assume the precision of the user, the user may use wei as well.

About JSON serialization, again, this is not the responsibility of the SDK to know if the user is serializing in JSON/YAML,protobuf... This is the user responsibility to know of to serialize in json.

A suggestion fron stack overflow is to use:

```ts
JSON.stringify(obj, (_, v) => typeof v === 'bigint' ? v.toString() : v)
```

when serializing in json.

2023-06-09 08:59 UTC, Darkness4 commented on src/index.ts
> +    loggerEndpoint = "grid-logger.deepsquare.run:443"
Yep

2023-06-22 09:45 UTC, efelem commented on pnpm-lock.yaml
Done

2023-06-22 10:26 UTC, merged